services:
  fastapi-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-review-backend
    ports:
      - "8000:8000"

  streamlit-frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: movie-review-frontend
    ports:
      - "8501:8501"
