FROM python:3.10-slim

# 작업 디렉토리 설정
WORKDIR /app

# Python 의존성 파일 복사
COPY pyproject.toml ./
COPY streamlit.py ./


RUN pip install uv
RUN uv pip install --system .


# 포트 노출
EXPOSE 8501

# Streamlit 애플리케이션 실행
CMD ["streamlit", "run", "streamlit.py", "--server.address", "0.0.0.0", "--server.port", "8501"] 