version: "3.8"

services:
  trainer:
    image: ys2357/re1-train:latest
    container_name: trainer_container
    command: ["python", "train_model.py"]

  jupyter:
    image: jupyter/base-notebook
    container_name: jupyter_container
    ports:
      - "8888:8888"
    volumes:
      - ./shared:/home/jovyan/shared
    command: start-notebook.sh